### ISSUE TITLE
佬可不可以大概说一下ck抓包流程

### ISSUE THREAD

**Issue by iedhgherljhfloj** [KimigaiiWuyi/WzryUID#16]

**Comment by Kloping** [comment]
bili搜app抓包教程

**Comment by KimigaiiWuyi** [comment]
安卓要root，抓营地，字段是token
苹果不用，有软件
没root的话可以用电脑模拟器，具体自己搜教程

**Comment by iedhgherljhfloj** [comment]
> 安卓要root，抓营地，字段是token 苹果不用，有软件 没root的话可以用电脑模拟器，具体自己搜教程

谢谢，o了
