### ISSUE TITLE
皮肤墙命令报错

### ISSUE THREAD

**Issue by chz091** [KimigaiiWuyi/WzryUID#18]
Task exception was never retrieved
future: <Task finished name='Task-33430' coro=<send_wzry_skin_list() done, defined at E:\gsuid_core\gsuid_core\sv.py:34> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "E:\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
    result = await func(bot, event)
  File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\__init__.py", line 21, in send_wzry_skin_list
    im = await _get_skin_list(user_id, uid)
  File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\get_skin_list.py", line 28, in _get_skin_list
    skin_info = data['skinCountInfo']
TypeError: string indices must be integers

**Comment by chz091** [comment]
> 最大可能是你服务器网络有问题,访问不到税某个应用程序接口请打开调试模式,并附带完整原木以便判断具体情况

04-12 15:41:52 [DEBUG] WzryUID.WzryUID.utils.api.request | {'retcode': -999, 'data': '<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>stgw</center>\r\n</body>\r\n</html>\r\n'}
Task exception was never retrieved
future: <Task finished name='Task-110' coro=<send_wzry_skin_list() done, defined at E:\gsuid_core\gsuid_core\sv.py:34> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "E:\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
    result = await func(bot, event)
  File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\__init__.py", line 21, in send_wzry_skin_list
    im = await _get_skin_list(user_id, uid)
  File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\get_skin_list.py", line 28, in _get_skin_list
    skin_info = data['skinCountInfo']
TypeError: string indices must be integers

**Comment by KimigaiiWuyi** [comment]
> > 最大可能是你服务器网络有问题,访问不到税某个应用程序接口请打开调试模式,并附带完整原木以便判断具体情况
> 
> 04-12 15:41:52 [DEBUG] WzryUID.WzryUID.utils.api.request | {'retcode': -999, 'data': '\r\n<title>503 Service Temporarily Unavailable</title>\r\n\r\n
> 
> # 503 Service Temporarily Unavailable
> \r\n
> stgw\r\n\r\n\r\n'}
> Task exception was never retrieved
> future: <Task finished name='Task-110' coro=<send_wzry_skin_list() done, defined at E:\gsuid_core\gsuid_core\sv.py:34> exception=TypeError('string indices must be integers')>
> Traceback (most recent call last):
> File "E:\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
> result = await func(bot, event)
> File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show__init__.py", line 21, in send_wzry_skin_list
> im = await _get_skin_list(user_id, uid)
> File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\get_skin_list.py", line 28, in _get_skin_list
> skin_info = data['skinCountInfo']
> TypeError: string indices must be integers

看来确实如此,你的服务器网络无法访问腾讯该API(503)
是哪个云服务商呢

**Comment by chz091** [comment]
> > > 最大可能是你服务器网络有问题,访问不到税某个应用程序接口请打开调试模式,并附带完整原木以便判断具体情况
> > 
> > 
> > 04-12 15:41:52 [DEBUG] WzryUID.WzryUID.utils.api.request | {'retcode': -999, 'data': '\r\n<title>503 Service Temporarily Unavailable</title>\r\n\r\n
> > # 503 Service Temporarily Unavailable
> > \r\n
> > stgw\r\n\r\n\r\n'}
> > Task exception was never retrieved
> > future: <Task finished name='Task-110' coro=<send_wzry_skin_list() done, defined at E:\gsuid_core\gsuid_core\sv.py:34> exception=TypeError('string indices must be integers')>
> > Traceback (most recent call last):
> > File "E:\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
> > result = await func(bot, event)
> > File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show__init__.py", line 21, in send_wzry_skin_list
> > im = await _get_skin_list(user_id, uid)
> > File "E:\gsuid_core\gsuid_core\plugins\WzryUID\WzryUID\wzryuid_skin_show\get_skin_list.py", line 28, in _get_skin_list
> > skin_info = data['skinCountInfo']
> > TypeError: string indices must be integers
> 
> 看来确实如此,你的服务器网络无法访问腾讯该API(503) 是哪个云服务商呢

家用服务器，用的移动宽带，开的虚拟机跑的机器人

**Comment by KimigaiiWuyi** [comment]
那估计没办法了, 可以通过尝试挂VPN解决

**Comment by chz091** [comment]
> 那估计没办法了, 可以通过尝试挂VPN解决

好的，我试试

**Comment by chz091** [comment]
> 那估计没办法了, 可以通过尝试挂VPN解决

佬，询问一下，这个调用的api地址是什么？

**Comment by KimigaiiWuyi** [comment]
> send_wzry_skin_list

https://ssl.kohsocialapp.qq.com:10001/play/h5getheroskinlist
是POST请求,需要携带很多参数,具体可参考
https://github.com/KimigaiiWuyi/WzryUID/blob/bcef0cc5a6699184e2f4abcf6d77a410b9a0c488/WzryUID/utils/api/request.py#L94-L136

**Comment by XiaoFuOS** [comment]
大佬怎么解决的，我也是这样报错，家里云，移动网
